force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Enter description here</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TaskController.cls
public with sharing class TaskController {
    
    @AuraEnabled(cacheable=true)
    public static List<Task__c> getUserTasks(String priority, String status) {
        String uId = UserInfo.getUserId();
        System.debug('Current User ID: ' + uId);
        String query = 'SELECT Id, Name, Description__c, Due_Date__c, Status__c, Priority__c, Assigned_To__c ' +
        'FROM Task__c WHERE Assigned_To__c = :uId';
        
        if (!String.isBlank(priority)) {
            query += ' AND Priority__c = \'' + priority + '\'';
        }
        if (!String.isBlank(status)) {
            query += ' AND Status__c = \'' + status + '\'';
        }
        System.debug('Query:'+query);
        return Database.query(query);
    }


    @AuraEnabled
    public static void createTask(Task__c newTask) {
        insert newTask;
    }

    @AuraEnabled
    public static void deleteTask(Id taskId) {
        try {
            Task__c task = [SELECT Id FROM Task__c WHERE Id = :taskId];
            delete task;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateTaskStatus(Id taskId, String newStatus) {
        Task__c task = [SELECT Status__c FROM Task__c WHERE Id = :taskId];
        task.Status__c = newStatus;
        update task;
    }
}